use_frameworks!
platform :ios, '9.0'

target 'SwiftI18n_Example' do
  pod 'SwiftI18n/I18n', :path => '../'

  target 'SwiftI18n_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end
